version: '3'

services: 
    php:
        container_name: php_laravel_node
        build: ./docker/php
        volumes:
            - ./myapp/:/var/www
    
    nginx:
        image: nginx
        container_name: nginx_laravel_node
        ports: 
            - 7080:80
        volumes:
            - ./myapp/:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php

    db:
        image: mysql
        container_name: db-host_laravel_node
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 7306:3306
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_laravel_node
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db-host
            - PMA_USER=docker
            - PMA_PASSWORD=docker
        links:
            - db
        ports:
            - 7180:80
        volumes:
            - /sessions